### ISSUE TITLE
Compile fails - node_events.h issue?

### ISSUE THREAD

**Issue by jfmercer** [huancz/node-snmp#3]
When I try to compile this module with node 0.6.2 on Ubuntu 10.10, it fails with an error reference to node_events.h. Has node_events.h been removed from node altogether? Based on [what I read here](https://github.com/joyent/node/commits/master/src/node_events.h), that seems to be the case. 

Any ideas? 

Here is the text of the error:

```
node-waf configure build
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /home/ubuntu/local/node/bin 
Checking for node prefix                 : ok /home/ubuntu/local/node 
'configure' finished successfully (0.034s)
Waf: Entering directory `/home/ubuntu/debian/build'
[1/2] cxx: src/snmp_binding.cc -> build/Release/src/snmp_binding_1.o
../src/snmp_binding.cc:24: fatal error: node_events.h: No such file or directory
compilation terminated.
Waf: Leaving directory `/home/ubuntu/debian/build'
Build failed:  -> task failed (err #1): 
    {task: cxx snmp_binding.cc -> snmp_binding_1.o}
```

**Comment by huancz** [comment]
Sorry for the delay, the notification drowned in my inbox...
1. The problem is not specific to Ubuntu:
   
   Checking for node prefix : ok /home/ubuntu/local/node -> you are not using ubuntu version of nodejs, it's custom version built from sources
2. Are you using current HEAD version of node-snmp? Commit cdb7fae7a14ad66bdcbc32c785df24ce44368e05 removed all mentions of node_events.h and should have fixed it at least on 0.5.x versions (confirmed on 0.5.10)... no idea about 0.6. Its not proper long term solution anyway. Node >= 0.6 is using another event library instead of libev - now it uses libuv developed specifically for node. On unix system it uses libev as lower layer and it is still accessible to modules due to headers including each other, but it looks like "undocumented" feature at best and it is not available on windows builds. Proper portable module would have to use libuv API.

According to [this](http://packages.ubuntu.com/precise/nodejs), even (currently pre-release) ubuntu version 12.04 will only offer package for nodejs-0.4.12. When they move to >0.5, I will likely get some company time to do the update. Until then, support for bleeding edge node depends on me getting home in mood to mess with this code, which is uncertain.
